# Generated by Django 5.1 on 2024-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_age', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
                ('teacher_course', models.CharField(max_length=20)),
                ('teacher_description', models.TextField()),
                ('teacher_occupation', models.CharField(max_length=20)),
                ('teacher_salary', models.PositiveIntegerField()),
                ('teacher_hobby', models.TextField()),
                ('teacher_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('teacher_headshot', models.ImageField(default='default_teacher_headshot.jpg', upload_to='')),
                ('classes', models.ManyToManyField(to='classroom.classroom')),
                ('courses', models.ManyToManyField(to='courses.courses')),
            ],
            options={
                'ordering': ['teacher_name'],
            },
        ),
    ]
