# Generated by Django 5.1 on 2024-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('teacher_id', models.PositiveIntegerField()),
                ('teacher_course', models.CharField(max_length=20)),
                ('teacher_occupation', models.CharField(max_length=20)),
                ('salary', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('teacher_headshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('assigned_classrooms', models.ManyToManyField(related_name='teachers_assigned', to='classroom.classroom')),
            ],
        ),
    ]
