# Generated by Django 5.1 on 2024-08-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classes',
            new_name='classrooms',
        ),
    ]
