# Generated by Django 5.1 on 2024-08-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=20)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_level', models.CharField(max_length=20)),
                ('maximum_attendees', models.PositiveSmallIntegerField()),
                ('course_exams', models.CharField(max_length=20)),
                ('course_fee', models.PositiveSmallIntegerField()),
                ('students', models.ManyToManyField(to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='teacher.teacher')),
            ],
        ),
    ]
