# Generated by Django 5.1 on 2024-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Period',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_period_classroom', models.CharField(max_length=20)),
                ('class_period_course_taught', models.CharField(max_length=20)),
                ('class_period_start_time', models.TimeField()),
                ('class_period_end_time', models.TimeField()),
                ('class_period_Day_of_the_week', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(to='courses.courses')),
                ('teacher', models.ManyToManyField(to='teacher.teacher')),
            ],
        ),
    ]
