# Generated by Django 5.1 on 2024-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=20)),
                ('course_syllabus', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_assigment', models.CharField(max_length=20)),
                ('course_level', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('course_exams', models.CharField(max_length=20)),
                ('course_duration', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
