# Generated by Django 5.1 on 2024-08-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial')
        
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='student.student', blank=True),
        ),
    ]
