# Generated by Django 5.1 on 2024-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=20)),
                ('code', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('name', models.CharField(default='Default Name', max_length=100)),
                ('classes', models.ManyToManyField(to='classroom.classroom')),
            ],
        ),
    ]
